export type EntityVehiclePrediction = {
    id: number
    year_of_manufacture: number
    model: string
    version: string
    color: string
    number_of_doors: number
    engine_power: number
    mileage: number
    oil_change_frequency: string
    filter_change_frequency: string
    engine_modifications: boolean
    critical_replacements: boolean
    documentation_in_order: boolean
    taxes_in_order: boolean
    technical_review_valid: boolean
    front_image: string
    left_side_image: string
    right_side_image: string
    rear_image: string
    engine_image: string
    interior_image: string
    seats_image: string
    dashboard_image: string
    valued_amount: string
    mae: number
    squared: number
    rmse: number
    evaluation_date: string
    brand: number
    fuel_type: number
    transmission_type: number
    traction_type: number
    body_condition: number
    chassis_condition: number
    brakes_condition: number
    suspension_condition: number
    exhaust_system_condition: number
    air_conditioning_condition: number
    electrical_system_condition: number
    user: number
    copied_user: any
}
